"""
Written by Irmen de Jong (irmen@razorvine.net)
Based on ancient soul.c v1.2 written in LPC by profezzorn@nannymud (Fredrik Hübinette)
Only the verb table is more or less intact (with some additions and fixes).
The verb parsing and message generation have been fully rewritten.

'Tale' mud driver, mudlib and interactive fiction framework
Copyright by Irmen de Jong (irmen@razorvine.net)
"""

from enum import Enum
from typing import Dict, Tuple


class VerbType(Enum):
    DEFA = 1  # adds HOW+AT   (you smile happily at Fritz)
    PREV = 2  # adds a WHO+HOW   (you ignore Fritz completely)
    PHYS = 3  # adds a WHO+HOW+WHERE  (you stroke Anna softly on the shoulder)
    SHRT = 4  # just adds a HOW, won't show a target  (you sweat profusely)
    PERS = 5  # provide an alternate WHO text  (you shiver with fear / you fear Fritz)
    SIMP = 6  # don't add stuff, the text itself has all escapes  (you snap your fingers at Fritz)
    DEUX = 7  # a room text is provided with alternate spelling or wording  (you fall down and play dead / Player falls to the ground, dead)
    QUAD = 8  # like DEUX, but also provides two more texts for when a target is used
    FULL = 9  # not used yet

# escapes used: AT, HOW, IS, MSG, MY, POSS, SUBJ, WHAT, WHERE, WHO, YOUR
# adverbs tuple: (adverb, message, where)
# if message starts with a ' (single quote), it will appear *without quotes*.

# Note: several verbs here are commented out because they are replaced by
# real commands or don't fit the game mechanics very well. It doesn't cause problems
# because they're just emotes, but it causes less confusion to disable them here.


VERBS = {
    "flex":      (VerbType.DEUX, None, "flex \nYOUR muscles \nHOW", "flexes \nYOUR muscles \nHOW"),
    "snort":     (VerbType.SIMP, None, "snort$ \nHOW \nAT", "at"),
    "pant":      (VerbType.SIMP, ("heavily", ), "pant$ \nHOW \nAT", "at"),
    "hmm":       (VerbType.SIMP, None, "hmm$ \nHOW \nAT", "at"),
    "ack":       (VerbType.SIMP, None, "ack$ \nHOW \nAT", "at"),
    "guffaw":    (VerbType.SIMP, None, "guffaw$ \nHOW \nAT", "at"),
    "raise":     (VerbType.SIMP, None, " \nHOW raise$ an eyebrow \nAT", "at"),
    "snap":      (VerbType.SIMP, None, "snap$ \nYOUR fingers \nAT", "at"),
    "lust":      (VerbType.DEFA, None, "", "for"),
    "burp":      (VerbType.DEFA, ("rudely", ), "", "at"),
    "bump":      (VerbType.DEFA, ("clumsily", ), "", "into"),
    "wink":      (VerbType.DEFA, ("suggestively", ), "", "at"),
    "smile":     (VerbType.DEFA, ("happily", ), "", "at"),
    "yawn":      (VerbType.DEFA, None, "", "at"),
    "swoon":     (VerbType.DEFA, ("romantically", ), "", "at"),
    "sneer":     (VerbType.DEFA, ("disdainfully", ), "", "at"),
    "talk":      (VerbType.SIMP, None, "want$ to talk \nAT \nHOW", "to"),
    "beam":      (VerbType.DEFA, None, "", "at"),
    "point":     (VerbType.DEFA, None, "", "at"),
    "grin":      (VerbType.DEFA, ("evilly", ), "", "at"),
    "laugh":     (VerbType.DEFA, None, "", "at"),
    "nod":       (VerbType.DEFA, ("solemnly", ), "", "at"),
    "wave":      (VerbType.DEFA, ("happily", ), "", "at"),
    "cackle":    (VerbType.DEFA, ("gleefully", ), "", "at"),
    "chuckle":   (VerbType.DEFA, None, "", "at"),
    "bow":       (VerbType.DEFA, None, "", "to"),
    "surrender": (VerbType.DEFA, None, "", "to"),
    "sit":       (VerbType.DEFA, ("down", ), "", "in front of"),
    "stand":     (VerbType.DEFA, ("up", ), "", "in front of"),
    "capitulate": (VerbType.DEFA, ("unconditionally", ), "", "to"),
    "glare":     (VerbType.DEFA, ("stonily", ), "", "at"),
    "giggle":    (VerbType.DEFA, ("merrily", ), "", "at"),
    "groan":     (VerbType.DEFA, None, "", "at"),
    "grunt":     (VerbType.DEFA, None, "", "at"),
    "growl":     (VerbType.DEFA, None, "", "at"),
    "breathe":   (VerbType.DEFA, ("heavily", ), "", "at"),
    "argh":      (VerbType.DEFA, None, "", "at"),
    "scowl":     (VerbType.DEFA, ("darkly", ), "", "at"),
    "snarl":     (VerbType.DEFA, None, "", "at"),
    "recoil":    (VerbType.DEFA, ("with fear", ), "", "from"),
    "moan":      (VerbType.DEFA, None, "", "at"),
    "howl":      (VerbType.DEFA, ("in pain", ), "", "at"),
    "puke":      (VerbType.DEFA, None, "", "on"),
    "drool":     (VerbType.DEFA, None, "", "on"),
    "sneeze":    (VerbType.DEFA, ("loudly", ), "", "at"),
    "spit":      (VerbType.DEFA, None, "", "on"),
    "stare":     (VerbType.DEFA, None, "", "at"),
    "whistle":   (VerbType.DEFA, ("appreciatively", ), "", "at"),
    "applaud":   (VerbType.DEFA, None, "", ""),
    "leer":      (VerbType.DEFA, None, "", "at"),
    "agree":     (VerbType.DEFA, None, "", "with"),
    "believe":   (VerbType.PERS, None, "believe$ in \nMYself \nHOW", "believe$ \nWHO \nHOW"),
    "understand": (VerbType.PERS, None, "understand$ \nHOW", "understand$ \nWHO \nHOW"),
    "disagree":  (VerbType.DEFA, None, "", "with"),
    "fart":      (VerbType.DEFA, None, "", "at"),
    "dance":     (VerbType.DEFA, None, "", "with"),
    "spin":      (VerbType.DEFA, ("dizzily",), "", "around"),
    "flirt":     (VerbType.DEFA, None, "", "with"),
    "meow":      (VerbType.DEFA, None, "", "at"),
    "bark":      (VerbType.DEFA, None, "", "at"),
    "slide":     (VerbType.SIMP, None, "slip$ and slide$ \nHOW"),
    "ogle":      (VerbType.PREV, None, ""),
    "eye":       (VerbType.PREV, ("suspiciously", ), ""),
    "pet":       (VerbType.SIMP, None, "pet$ \nWHO \nHOW \nWHERE"),
    "barf":      (VerbType.DEFA, None, "", "on"),
    "listen":    (VerbType.DEFA, None, "", "to"),
    "hear":      (VerbType.SIMP, None, "listen$ \nAT \nHOW", "to"),        # the same effect as listen
    "purr":      (VerbType.DEFA, None, "", "at"),
    "curtsy":    (VerbType.DEFA, None, "", "before"),
    "puzzle":    (VerbType.SIMP, None, "look$ \nHOW puzzled \nAT", "at"),
    "grovel":    (VerbType.DEFA, None, "", "before"),
    "tongue":    (VerbType.SIMP, None, "stick$ \nYOUR tongue out \nHOW \nAT", "at"),
    "swing":     (VerbType.SIMP, ("wildly", ), "swing$ \nYOUR arms \nHOW \nAT", "at"),
    "apologize": (VerbType.DEFA, None, "", "to"),
    "sorry":     (VerbType.SIMP, None, "apologize$ \nAT \nHOW", "to"),
    "complain":  (VerbType.DEFA, None, "", "about"),
    "rotate":    (VerbType.PERS, None, "rotate$ \nHOW", "rotate$ \nWHO \nHOW"),        # overridden by a cmd
    "excuse":    (VerbType.PERS, None, " \nHOW excuse$ \nMYself", " \nHOW excuse$ \nMYself to \nWHO"),
    "beg":       (VerbType.PERS, None, "beg$ \nHOW", "beg$ \nWHO for mercy \nHOW"),
    "fear":      (VerbType.PERS, None, "shiver$ \nHOW with fear", "fear$ \nWHO \nHOW"),
    "headshake": (VerbType.SIMP, None, "shake$ \nYOUR head \nAT \nHOW", "at"),
    "shake":     (VerbType.SIMP, ("like a bowlful of jello", ), "shake$ \nAT \nHOW", ""),
    "jiggle":    (VerbType.SIMP, ("like a bowlful of jello", ), "jiggle$ \nAT \nHOW", ""),
    "stink":     (VerbType.PERS, None, "smell$ \nYOUR armpits. Eeeww!", "smell$ \nPOSS armpits. Eeeww!"),
    "grimace":   (VerbType.SIMP, None, " \nHOW make$ an awful face \nAT", "at"),
    "stomp":     (VerbType.PERS, None, "stomp$ \nYOUR foot \nHOW", "stomp$ on \nPOSS foot \nHOW"),
    "snigger":   (VerbType.DEFA, ("jeeringly", ), "", "at"),
    "watch":     (VerbType.QUAD, ("carefully", ), "watch the surroundings \nHOW", "watches the surroundings \nHOW",
                  "watch \nWHO \nHOW", "watches \nWHO \nHOW", ),
    "scratch":   (VerbType.QUAD, (None, None, "on the head"), "scratch \nMYself \nHOW \nWHERE", "scratches \nMYself \nHOW \nWHERE",
                  "scratch \nWHO \nHOW \nWHERE", "scratches \nWHO \nHOW \nWHERE", ),
    "tap":       (VerbType.PERS, ("impatiently", None, "on the shoulder"), "tap$ \nYOUR foot \nHOW", "tap$ \nWHO \nWHERE"),
    "wobble":    (VerbType.SIMP, None, "wobble$ \nAT \nHOW", ""),
    "move":      (VerbType.SIMP, ("thoughtfully", ), "move$ out of the way \nHOW", ""),
    "yodel":     (VerbType.SIMP, None, "yodel$ a merry tune \nHOW", ""),
    "spray":     (VerbType.SIMP, None, "spray$ \nHOW \nAT", "all over"),
    "spill":     (VerbType.SIMP, None, "spill$ \nYOUR drink \nHOW \nAT", "all over"),
    "melt":      (VerbType.PERS, ("in front of",), "melt$ from the heat", "melt$ \nHOW \nWHO"),
    "hello":     (VerbType.PERS, None, "greet$ everyone \nHOW", "greet$ \nWHO \nHOW"),
    "hi":        (VerbType.PERS, None, "greet$ everyone \nHOW", "greet$ \nWHO \nHOW"),
    "wait":      (VerbType.SIMP, None, "wait$ \nHOW", ""),   # replaced by a command
    "grease":    (VerbType.SIMP, ("like a shiatsu",), "grease$ \nWHO \nHOW"),
    "oil":       (VerbType.SIMP, ("like a shiatsu",), "oil$ \nWHO \nHOW"),
    "search":    (VerbType.DEUX, ("thoroughly",), "search \nWHO \nHOW, where is it?", "searches \nWHO \nHOW, where is it?"),  # XXX replace by command?
    "sniff":     (VerbType.PERS, None, "sniff$. What's that smell?", "sniff$ \nWHO. What's that smell?"),
    "smell":     (VerbType.PERS, None, "sniff$. What's that smell?", "sniff$ \nWHO. What's that smell?"),
    "smoke":     (VerbType.PERS, None, "smoke$ a cigar, and blow$ out the smoke.", "smoke$ a cigar, and blow$ the smoke at \nWHO."),

    # Message-based verbs
    "curse":     (VerbType.PERS, None, "curse$ \nWHAT \nHOW", "curse$ \nWHO \nHOW"),
    "swear":     (VerbType.SIMP, None, "swear$ \nWHAT \nAT \nHOW", "before"),
    "criticize": (VerbType.PERS, None, "criticize$ \nWHAT \nHOW", "criticize$ \nWHO \nHOW"),
    "lie":       (VerbType.PERS, None, "lie$ \nMSG \nHOW", "lie$ to \nWHO \nHOW"),
    "mutter":    (VerbType.PERS, (None, "ehh..."), "mutter$ \nMSG \nHOW", "mutter$ \nMSG to \nWHO \nHOW"),
    "say":       (VerbType.SIMP, (None, "'nothing"), " say$ \nAT: \nWHAT", "to"),    # XXX replace by a command?
    "babble":    (VerbType.SIMP, ("incoherently", "'something"), "babble$ \nMSG \nHOW \nAT", "to"),
    "chant":     (VerbType.SIMP, (None, "Hare Krishna Krishna Hare Hare"), " \nHOW chant$: \nWHAT", ""),
    "sing":      (VerbType.SIMP, None, "sing$ \nWHAT \nHOW \nAT", "to"),
    "hiss":      (VerbType.QUAD, None, "hiss \nMSG \nHOW", "hisses \nMSG \nHOW", "hiss \nMSG to \nWHO \nHOW", "hisses \nMSG to \nWHO \nHOW", ),
    "answer":    (VerbType.SIMP, (None, "ehh..."), " \nHOW answer$ \nAT: \nWHAT", ""),
    "reply":     (VerbType.QUAD, (None, "ehh..."), " \nHOW reply: \nWHAT", " \nHOW replies: \nWHAT",
                  " \nHOW reply to \nWHO: \nWHAT", " \nHOW replies to \nWHO: \nWHAT"),
    "exclaim":   (VerbType.SIMP, (None, "no way"), " \nHOW exclaim$ \nAT: \nWHAT!", ""),
    "quote":     (VerbType.SIMP, None, " \nHOW quote$ \nAT \nMSG", "to"),
    "ask":       (VerbType.SIMP, (None, "ehh..."), " \nHOW ask$ \nAT: \nWHAT?", ""),
    "request":   (VerbType.SIMP, (None, "a moment"), " \nHOW request$ \nAT \nWHAT", ""),
    "consult":   (VerbType.SIMP, None, " \nHOW consult$ \nAT \nWHAT", ""),
    "mumble":    (VerbType.SIMP, None, "mumble$ \nMSG \nHOW \nAT", "to"),
    "murmur":    (VerbType.SIMP, None, "murmur$ \nMSG \nHOW \nAT", "to"),
    "scream":    (VerbType.SIMP, ("loudly", ), "scream$ \nMSG \nHOW \nAT", "at"),     # XXX replaced by a command
    "yell":      (VerbType.SIMP, ("in a high pitched voice", ), "yell$ \nMSG \nHOW \nAT", "at"),    # XXX replaced by a command
    "command":   (VerbType.SIMP, (None, "follow orders"), "command$ \nWHO \nHOW to \nWHAT"),
    "utter":     (VerbType.SIMP, (None, "ehh..."), " \nHOW utter$ \nMSG \nAT", "to"),
    "whisper":   (VerbType.SIMP, None, "whisper$ \nMSG \nHOW \nAT", "to"),
    "emote":     (VerbType.DEUX, None, "emote: player \nWHAT", " \nWHAT"),   # XXX replaced by a command

    # Verbs that require a person
    "glance":    (VerbType.SIMP, None, "glance$ \nHOW at \nWHO"),
    "hide":      (VerbType.SIMP, None, "hide$ \nHOW behind \nWHO"),
    "finger":    (VerbType.SIMP, None, "give$ \nWHO the finger"),
    "mercy":     (VerbType.SIMP, None, "beg$ \nWHO for mercy"),
    "jerk":      (VerbType.SIMP, ("briskly", ), "jerk$ \nWHO \nHOW", ""),
    "insult":    (VerbType.SIMP, ("angrily", ), " \nHOW spew$ profanities at \nWHO"),
    "gripe":     (VerbType.PREV, None, "to"),
    "peer":      (VerbType.PREV, None, "at"),
    "gaze":      (VerbType.PREV, None, "at"),
    "chase":     (VerbType.PREV, ("angrily",), "after"),
    "remember":  (VerbType.SIMP, None, "remember$ \nAT \nHOW", ""),
    "surprise":  (VerbType.PREV, None, ""),
    "pounce":    (VerbType.PHYS, ("playfully", ), ""),
    "feel":      (VerbType.PHYS, ("softly", ), ""),
    "bite":      (VerbType.PERS, None, " \nHOW bite$ \nYOUR lip", "bite$ \nWHO \nHOW \nWHERE"),
    "lick":      (VerbType.SIMP, None, "lick$ \nWHO \nHOW \nWHERE"),
    "caper":     (VerbType.PERS, ("merrily", ), "caper$ \nHOW about", "caper$ around \nWHO \nHOW"),
    "beep":      (VerbType.PERS, ("triumphantly", None, "on the nose"), " \nHOW beep$ \nMYself \nWHERE", " \nHOW beep$ \nWHO \nWHERE"),
    "blink":     (VerbType.PERS, None, "blink$ \nHOW", "blink$ \nHOW at \nWHO"),
    "knock":     (VerbType.PHYS, (None, None, "on the head"), ""),
    "bonk":      (VerbType.PHYS, (None, None, "on the head"), ""),
    "bop":       (VerbType.PHYS, (None, None, "on the head"), ""),
    "stroke":    (VerbType.PHYS, (None, None, "on the cheek"), ""),
    "shove":     (VerbType.PHYS, ("briskly", None, "to the side"), ""),
    "push":      (VerbType.PHYS, (None, None, "to the side"), ""),
    "pull":      (VerbType.SIMP, None, "pull$ at \nWHO"),
    "rub":       (VerbType.PHYS, ("gently", None, "on the back"), ""),
    "hold":      (VerbType.PHYS, (None, None, "in \nYOUR arms"), ""),
    "embrace":   (VerbType.PHYS, (None, None, "in \nYOUR arms"), ""),
    "handshake": (VerbType.SIMP, None, "shake$ hands with \nWHO", ""),
    "tickle":    (VerbType.PREV, None, ""),
    "worship":   (VerbType.PREV, None, ""),
    "admire":    (VerbType.PREV, None, ""),
    "mock":      (VerbType.PREV, None, ""),
    "tease":     (VerbType.PREV, None, ""),
    "taunt":     (VerbType.PREV, None, ""),
    "strangle":  (VerbType.PREV, None, ""),
    "hate":      (VerbType.PREV, None, ""),
    "kill":      (VerbType.PREV, None, ""),
    "attack":    (VerbType.PREV, None, ""),
    "fight":     (VerbType.PREV, None, ""),
    "fondle":    (VerbType.PREV, None, ""),
    "nominate":  (VerbType.PREV, None, ""),
    "startle":   (VerbType.PREV, None, ""),
    "lift":      (VerbType.PREV, ("from the floor", ), ""),   # XXX doesn't fit game mechanics
    "turn":      (VerbType.PREV, None, "\nYOUR head towards"),
    "squeeze":   (VerbType.PREV, ("fondly", ), ""),
    "comfort":   (VerbType.PREV, None, ""),
    "nudge":     (VerbType.PHYS, ("suggestively", ), ""),
    "slap":      (VerbType.PHYS, (None, None, "in the face"), ""),
    "hit":       (VerbType.PHYS, (None, None, "in the face"), ""),
    "kick":      (VerbType.PHYS, ("hard", ), ""),
    "tackle":    (VerbType.SIMP, None, "tackle$ \nWHO \nHOW", ""),
    "tell":      (VerbType.SIMP, None, "tell$ \nWHO \nMSG", ""),     # XXX replaced by a command
    "spank":     (VerbType.PHYS, (None, None, "on the butt"), ""),
    "pat":       (VerbType.PHYS, (None, None, "on the head"), ""),
    "punch":     (VerbType.DEUX, (None, None, "in the eye"), "punch \nWHO \nHOW \nWHERE", "punches \nWHO \nHOW \nWHERE"),
    "hug":       (VerbType.PREV, None, ""),
    "want":      (VerbType.PREV, None, ""),
    "pinch":     (VerbType.DEUX, None, "pinch \nWHO \nHOW \nWHERE", "pinches \nWHO \nHOW \nWHERE"),
    "kiss":      (VerbType.DEUX, None, "kiss \nWHO \nHOW \nWHERE", "kisses \nWHO \nHOW \nWHERE"),
    "caress":    (VerbType.DEUX, (None, None, "on the cheek"), "caress \nWHO \nHOW \nWHERE", "caresses \nWHO \nHOW \nWHERE"),
    "smooch":    (VerbType.DEUX, None, "smooch \nWHO \nHOW", "smooches \nWHO \nHOW"),
    "envy":      (VerbType.DEUX, None, "envy \nWHO \nHOW", "envies \nWHO \nHOW"),
    "touch":     (VerbType.DEUX, None, "touch \nWHO \nHOW \nWHERE", "touches \nWHO \nHOW \nWHERE"),
    "knee":      (VerbType.PHYS, (None, None, "where it hurts"), ""),
    "love":      (VerbType.PREV, None, ""),
    "adore":     (VerbType.PREV, None, ""),
    "grope":     (VerbType.PREV, None, ""),
    "poke":      (VerbType.PHYS, (None, None, "in the ribs"), ""),
    "snuggle":   (VerbType.PREV, None, ""),
    "kneel":     (VerbType.SIMP, None, " \nHOW fall$ on \nYOUR knees \nAT", "in front of"),
    "trust":     (VerbType.PREV, None, ""),
    "like":      (VerbType.PREV, None, ""),
    "greet":     (VerbType.PREV, None, ""),
    "welcome":   (VerbType.PREV, None, ""),
    "thank":     (VerbType.PREV, None, ""),
    "cuddle":    (VerbType.PREV, None, ""),
    "salute":    (VerbType.PREV, None, ""),
    "french":    (VerbType.SIMP, None, "give$ \nWHO a REAL kiss, it seems to last forever"),
    "nibble":    (VerbType.SIMP, None, "nibble$ \nHOW on \nPOSS ear"),
    "ruffle":    (VerbType.SIMP, None, "ruffle$ \nPOSS hair \nHOW"),
    "ignore":    (VerbType.PREV, None, ""),
    "forgive":   (VerbType.PREV, None, ""),
    "congratulate": (VerbType.PREV, None, ""),
    "ayt":       (VerbType.SIMP, None, "wave$ \nYOUR hand in front of \nPOSS face, \nIS \nSUBJ \nHOW there?"),
    "judge":     (VerbType.PREV, None, "", ),

    # Verbs that don't need, nor use persons
    "roll":      (VerbType.SIMP, ("to the ceiling", ), "roll$ \nYOUR eyes \nHOW"),
    "boggle":    (VerbType.SIMP, None, "boggle$ \nHOW at the concept"),
    "cheer":     (VerbType.SHRT, ("enthusiastically", ), ""),
    "twiddle":   (VerbType.SIMP, None, "twiddle$ \nYOUR thumbs \nHOW"),
    "wiggle":    (VerbType.SIMP, None, "wiggle$ \nYOUR bottom \nAT \nHOW", "at"),
    "wrinkle":   (VerbType.SIMP, None, "wrinkle$ \nYOUR nose \nAT \nHOW", "at"),
    "thumb":     (VerbType.SIMP, None, " \nHOW suck$ \nYOUR thumb"),
    "flip":      (VerbType.SIMP, None, "flip$ \nHOW head over heels"),
    "cry":       (VerbType.DEUX, None, "cry \nHOW", "cries \nHOW"),
    "ah":        (VerbType.DEUX, None, "go 'ah' \nHOW", "goes 'ah' \nHOW"),
    "halt!":     (VerbType.DEUX, None, "go 'Halt! Hammerzeit!' \nHOW", "goes 'Halt! Hammerzeit!' \nHOW"),
    "stop!":     (VerbType.DEUX, None, "go 'Stop! Hammertime!' \nHOW", "goes 'Stop! Hammertime!' \nHOW"),
    "clear":     (VerbType.SIMP, None, "clear$ \nYOUR throat \nHOW"),
    "sob":       (VerbType.SHRT, None, ""),
    "lag":       (VerbType.SHRT, ("helplessly", ), ""),
    "whine":     (VerbType.SHRT, None, ""),
    "cringe":    (VerbType.SIMP, ("in terror", ), "cringe$ \nHOW"),
    "sweat":     (VerbType.SHRT, None, ""),
    "gurgle":    (VerbType.SHRT, None, ""),
    "grumble":   (VerbType.SHRT, None, ""),
    "panic":     (VerbType.SHRT, None, ""),
    "pace":      (VerbType.SIMP, ("impatiently", ), "start$ pacing \nHOW"),
    "pale":      (VerbType.SIMP, None, "turn$ white as ashes \nHOW"),
    "die":       (VerbType.DEUX, None, " \nHOW fall down and play dead", " \nHOW falls to the ground, dead"),
    # "sleep":    (VerbType.DEUX, ("soundly", ), "fall asleep \nHOW", "falls asleep \nHOW"),
    "sleep":     (VerbType.SIMP, None, "yawn$ sleepily"),
    # "wake":     (VerbType.SIMP, ("groggily", ), "awake$ \nHOW"),
    "wake":      (VerbType.DEUX, None, "are awake", "is awake"),
    # "awake":    (VerbType.SIMP, ("groggily", ), "awake$ \nHOW"),
    "awake":     (VerbType.DEUX, None, "are awake", "is awake"),
    "stumble":   (VerbType.SHRT, None, ""),
    "bounce":    (VerbType.SHRT, ("up and down", ), ""),
    "sulk":      (VerbType.SHRT, ("in the corner", ), ""),
    "strut":     (VerbType.SHRT, ("proudly", ), ""),
    "snivel":    (VerbType.SHRT, ("pathetically", ), ""),
    "snore":     (VerbType.SHRT, None, ""),
    "clue":      (VerbType.SIMP, None, "need$ a clue \nHOW"),
    "stupid":    (VerbType.SIMP, None, "look$ \nHOW stupid"),
    "bored":     (VerbType.SIMP, None, "look$ \nHOW bored"),
    "repent":    (VerbType.SIMP, None, "repent$ \nYOUR sins"),
    "snicker":   (VerbType.SHRT, None, ""),
    "smirk":     (VerbType.SHRT, None, ""),
    "jump":      (VerbType.SIMP, ("up and down in aggravation", ), "jump$ \nHOW"),
    "squint":    (VerbType.SHRT, None, ""),
    "huff":      (VerbType.SHRT, None, ""),
    "puff":      (VerbType.SHRT, None, ""),
    "fume":      (VerbType.SHRT, None, ""),
    "steam":     (VerbType.SHRT, None, ""),
    "choke":     (VerbType.SHRT, None, ""),
    "faint":     (VerbType.SHRT, None, ""),
    "shrug":     (VerbType.SHRT, None, ""),
    "pout":      (VerbType.SHRT, None, ""),
    "hiccup":    (VerbType.SHRT, None, ""),
    "frown":     (VerbType.SHRT, None, ""),
    "pray":      (VerbType.SIMP, None, "mumble$ a short prayer \nAT", "to"),
    "gasp":      (VerbType.SHRT, ("in astonishment", ), ""),
    "think":     (VerbType.SHRT, ("carefully", ), ""),
    "ponder":    (VerbType.SHRT, ("over some problem", ), ""),
    "wonder":    (VerbType.DEFA, None, "", "at"),
    "clap":      (VerbType.SHRT, None, ""),
    "sigh":      (VerbType.SHRT, None, ""),
    "cough":     (VerbType.SHRT, ("noisily", ), ""),
    "shiver":    (VerbType.SHRT, ("from the cold", ), ""),
    "tremble":   (VerbType.SHRT, None, ""),
    "twitch":    (VerbType.DEUX, None, "twitch \nHOW", "twitches \nHOW"),
    "bitch":     (VerbType.DEUX, None, "bitch \nHOW", "bitches \nHOW"),
    "blush":     (VerbType.DEUX, None, "blush \nHOW", "blushes \nHOW"),
    "stretch":   (VerbType.DEUX, None, "stretch \nHOW", "stretches \nHOW"),
    "relax":     (VerbType.DEUX, None, "relax \nHOW", "relaxes \nHOW"),
    "duck":      (VerbType.PERS, None, "duck$ \nHOW out of the way", "duck$ \nHOW out of \nPOSS way"),
}  # type: Dict[str, Tuple]


assert all(v[1] is None or type(v[1]) is tuple for v in VERBS.values()), "Second specifier in verb list must be None or tuple, not str"

AGGRESSIVE_VERBS = {
    "attack", "barf", "bitch", "bite", "bonk", "bop", "bump", "burp", "caress", "chase", "curse", "feel", "fight",
    "finger", "fondle", "french", "grease", "grimace", "grope", "growl", "guffaw", "handshake", "hit", "hold", "hug",
    "insult", "jerk", "jiggle", "kick", "kill", "kiss", "knee", "knock", "lick", "mock", "nibble", "nudge", "oil",
    "pat", "pet", "pinch", "poke", "pounce", "puke", "push", "pull", "punch", "rotate", "rub", "ruffle", "scowl",
    "scratch", "shake", "shove", "slap", "smooch", "sneer", "snigger", "snuggle", "spank", "spill", "spit", "spray",
    "squeeze", "startle", "stomp", "strangle", "stroke", "surprise", "swing", "tackle", "tap", "taunt", "tease",
    "tickle", "tongue", "touch", "wiggle", "wobble", "wrinkle"
}

assert AGGRESSIVE_VERBS.issubset(VERBS.keys())

NONLIVING_OK_VERBS = {
    "admire", "adore", "answer", "argh", "ask", "babble", "barf", "bark", "beam",
    "bite", "blink", "bow", "breathe", "bump", "cackle", "caper", "capitulate",
    "chuckle", "complain", "cuddle", "curse", "drool", "embrace", "eye", "fear",
    "feel", "finger", "fondle", "gaze", "giggle", "glare", "glance", "grimace", "grin", "groan",
    "grope", "growl", "grunt", "guffaw", "hate", "headshake", "hide", "hiss",
    "hmm", "ignore", "jerk", "judge", "kick", "laugh", "leer", "lick", "like", "listen",
    "love", "lust", "meow", "moan", "mumble", "murmur", "mutter", "nod", "nominate",
    "ogle", "peer", "point", "puke", "pull", "push", "purr", "puzzle", "quote",
    "raise", "recoil", "reply", "rotate", "scowl", "shake",
    "shove", "sing", "smile", "snap", "snarl", "sneer", "sneeze", "smell", "sniff",
    "snigger", "snort", "spill", "spin", "spit", "spray", "stare", "surrender",
    "swing", "squeeze", "tongue", "touch", "trust", "turn", "understand", "utter", "want",
    "watch", "wave", "wiggle", "wobble", "worship", "wrinkle", "yawn"
}

assert NONLIVING_OK_VERBS.issubset(VERBS.keys())

MOVEMENT_VERBS = {"go", "enter", "walk", "climb", "crawl", "move", "flee", "run", "hurry", "sprint"}

ACTION_QUALIFIERS = {
    # qualifier -> (actionmsg, roommsg, use room actionstr)     # XXX what is room actionstr exactly
    "suddenly": ("suddenly %s", "suddenly %s", True),
    "fail": ("try to %s, but fail miserably", "tries to %s, but fails miserably", False),
    "again": ("%s again", "%s again", True),
    "pretend": ("pretend to %s", "pretends to %s", False),
    "dont": ("don't %s", "doesn't %s", False),
    "don't": ("don't %s", "doesn't %s", False),
    "attempt": ("attempt to %s, without much success", "attempts to %s, without much success", False)
}

NEGATING_QUALIFIERS = {"fail", "pretend", "dont", "don't", "attempt"}

assert NEGATING_QUALIFIERS.issubset(ACTION_QUALIFIERS.keys())

BODY_PARTS = {
    "hand": "on the hand",
    "forehead": "on the forehead",
    "head": "on the head",
    "kneecap": "on the kneecap",
    "ankle": "in the ankle",
    "knee": "on the knee",
    "face": "in the face",
    "hurts": "where it hurts",
    "nuts": "where it hurts",
    "kidney": "in the kidneys",
    "temple": "on the temple",
    "eye": "in the eye",
    "ear": "on the ear",
    "stomach": "in the stomach",
    "butt": "on the butt",
    "behind": "on the behind",
    "leg": "on the leg",
    "foot": "on the foot",
    "toe": "on the right toe",
    "nose": "on the nose",
    "neck": "in the neck",
    "back": "on the back",
    "arm": "on the arm",
    "elbow": "on the elbow",
    "wrist": "on the wrist",
    "chest": "on the chest",
    "cheek": "on the cheek",
    "side": "in the side",
    "shoulder": "on the shoulder",
    "everywhere": "everywhere",
}
